### ISSUE TITLE
Error `forgotten to call 'done'` since version 3.4

### ISSUE THREAD

**Issue by mpsq** [fastify/fastify-type-provider-typebox#104]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the regression has not already been reported

### Last working version

3.3

### Stopped working in version

3.4 (including 3.5)

### Node.js version

20.4

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

Archlinux / Not applicable

### 💥 Regression Report

With no code change, this library is now breaking with:

```
    FastifyError: fastify-plugin: Plugin did not start in time: 'bound _encapsulateThreeParam'. You may have forgotten to call 'done' function or to resolve a Promise

      at manageErr (../../node_modules/fastify/fastify.js:588:33)
      at ../../node_modules/fastify/fastify.js:575:11
      at Object._encapsulateThreeParam (../../node_modules/avvio/boot.js:562:7)
      at Boot.timeoutCall (../../node_modules/avvio/boot.js:458:5)
      at Boot.callWithCbOrNextTick (../../node_modules/avvio/boot.js:440:19)
      at Task.release (../../node_modules/fastq/queue.js:149:16)
      at worked (../../node_modules/fastq/queue.js:201:10)
      at Timeout._onTimeout (../../node_modules/avvio/boot.js:454:5)
```

The same code works fine in `3.3` (breaks in `3.4` and `3.5`)

### Steps to Reproduce

```typescript
import { Type } from "@fastify/type-provider-typebox"
import { FastifyPluginCallback, FastifyPluginOptions } from "fastify"
import fp from "fastify-plugin"

const DummyMessage = Type.String({
  $id: "dummyMessage",
  title: "Dummy Message",
  description: "A dummy message.",
})

const schemasCallback: FastifyPluginCallback<FastifyPluginOptions> = (
  fastify,
  _,
  done,
) => {
  fastify.addSchema(DummyMessage)

  done()
}

export default fp(schemasCallback)
```

**Comment by mpsq** [comment]
I just tried and I get the same issue, I will update the OP with your version since it is simpler

**Comment by mcollina** [comment]
Can you please include a full example?

**Comment by mpsq** [comment]
Of course, the init is done with:

```typescript
import { Type } from "@fastify/type-provider-typebox"
import Fastify, { FastifyPluginCallback, FastifyPluginOptions } from "fastify"
import fp from "fastify-plugin"

const DummyMessage = Type.String({
  $id: "dummyMessage",
  title: "Dummy Message",
  description: "A dummy message.",
})

const schemasCallback: FastifyPluginCallback<FastifyPluginOptions> = (
  fastify,
  _,
  done,
) => {
  fastify.addSchema(DummyMessage)

  done()
}

const schemas = fp(schemasCallback)

const fastify = Fastify({
  disableRequestLogging: true,
}).withTypeProvider<TypeBoxTypeProvider>()
// ...
await fastify.register(schemas)
```

**Comment by mcollina** [comment]
The following works as expected:

```ts
import { Type, TypeBoxTypeProvider } from "./index"
import Fastify, { FastifyPluginCallback, FastifyPluginOptions } from "fastify"
import fp from "fastify-plugin"

const DummyMessage = Type.String({
  $id: "dummyMessage",
  title: "Dummy Message",
  description: "A dummy message.",
})

const schemasCallback: FastifyPluginCallback<FastifyPluginOptions> = (
  fastify,
  _,
  done,
) => {
  fastify.addSchema(DummyMessage)

  done()
}

const schemas = fp(schemasCallback)

async function init() {
  const fastify = Fastify({
    disableRequestLogging: true,
  }).withTypeProvider<TypeBoxTypeProvider>()
  await fastify.register(schemas)
  return fastify
}

init().then(() => {
  console.log('booted')
})
```

I think we would need a full repository with all your settings.

**Comment by mpsq** [comment]
@mcollina 

I managed to identify the problem, in this snippet:

```typescript
const routes: FastifyPluginCallback<FastifyPluginOptions> = (
  fastify,
  _,
  done,
) => {
  fastify.get(
    "/",
    {
      schema: {
        operationId: "dummy",
        response: {
          204: Type.Void(), // Type.Undefined() produces the same result
        },
      },
    },
    async (req, reply) => {
      return reply.code(204).send()
    }
  )
  done()
}
```

The lines:

```
       response: {
          204: Type.Void(), // Type.Undefined() produces the same result
        },
```

Will make Fastify throw with:

```
    FastifyError: fastify-plugin: Plugin did not start in time: 'bound _encapsulateThreeParam'. You may have forgotten to call 'done' function or to resolve a Promise
```

This used to work with `@fastify/fastify-type-provider-typebox/issues` 3.3. I imagine that this is a `typebox` problem and that this plugin has nothing to do with it?
If yes, feel free to close this ticket :)

**Comment by Uzlopak** [comment]
@sinclairzx81 
fyi

**Comment by sinclairzx81** [comment]
@mpsq @Uzlopak Hiya,

The Void and Undefined types are extension types in TypeBox. They cannot be used with Json Schema validators as Json has no concept of `undefined`. Because of this you should avoid using with these types when using Ajv. 

Documentation on the types can be found below

https://github.com/sinclairzx81/typebox#types-javascript

> TypeBox provides an extended type set that can be used to create schematics for common JavaScript constructs. These types can not be used with any standard Json Schema validator; but can be used to frame schematics for interfaces that may receive Json validated data. JavaScript types are prefixed with the `[JavaScript]` jsdoc comment for convenience

Hope this helps
S

**Comment by mpsq** [comment]
Thanks for the quick answer.
This makes total sense :pray:
