### ISSUE TITLE
preHandler types conflict with package `@fastify/auth`

### ISSUE THREAD

**Issue by TheWashiba** [fastify/fastify-type-provider-typebox#5]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.0.0-rc.3

### Node.js version

16.x

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

Ubuntu 20.04

### Description

I'm having TypeScript issues in the route `preHandler` when the package `@fastify/auth` ^3.0.0 is being used altogether. I'm unsure if this an issue of that package or this, but I've began experiencing issues once `.withTypeProvider<TypeBoxTypeProvider>()` is called. The error received:
```
Type 'preHandlerHookHandler<Server, IncomingMessage, ServerResponse, RouteGenericInterface, unknown, FastifySchema, FastifyTypeProviderDefault, ResolveFastifyRequestType<...>, FastifyLoggerInstance>' is not assignable to type 'preHandlerHookHandler<Server, IncomingMessage, ServerResponse, RouteGenericInterface, unknown, FastifySchema, TypeBoxTypeProvider, ResolveFastifyRequestType<...>, FastifyLoggerInstance> | preHandlerHookHandler<...>[] | undefined'.
```

### Steps to Reproduce

Install `fastify@4`, `@fastify/auth@3` and `.1.0-beta.1` version of this plugin in a TypeScript environment. Calling the `fastify.auth([])` in the route `preHandler` will give a type error.

**Comment by mcollina** [comment]
cc @fastify/typescript could you take a look?

**Comment by mcollina** [comment]
Could you create a repo with the setup that is not working?

**Comment by TheWashiba** [comment]
@mcollina here you go https://github.com/TheWashiba/fastify-typescript-bug

**Comment by mcollina** [comment]
thx, I'll take a look asap

**Comment by mcollina** [comment]
@fastify/typescript can you take a look as well? I'm kind of unsure what's the problem.

**Comment by mcollina** [comment]
@kibertoad @fox1t @Eomm could you take a look?

**Comment by kibertoad** [comment]
on it

**Comment by TheWashiba** [comment]
Any news about it?

**Comment by fox1t** [comment]
First of all, sorry for the late response. I've just looked into this, and it turns out that the issue is indeed the `.withTypeProvider<TypeBoxTypeProvider>()` call. 


`@fastify/auth arguments fastify instance with auth method that is a preHandlerHookHandler that uses the default type provider https://github.com/fastify/fastify-auth/blob/master/auth.d.ts#L18
This clashes with your fastify instance that uses TypeBox TypeProvider. 

Unfortunately, at the moment, I don't have a solution. I will look more deeply into this and return if anything comes to mind.

**Comment by mcollina** [comment]
cc @sinclairzx81

**Comment by sinclairzx81** [comment]
@mcollina @TheWashiba Hi. Had a brief look at this the other day. The issue appears to be caused by the `server.auth([])` function returning a function signature that is globally typed to use the `FastifyTypeProvider` (not the `TypeBoxTypeProvider` as configured).  As such the assignment of `server.auth([])` on the `preHandler` is the primary source of this type error as the Provider types are incompatible (as mentioned by @fox1t )

Unfortunately, because the `auth()` function is globally typed (using module augmentation [here](https://github.com/fastify/fastify-auth/blob/master/auth.d.ts#L10-L20)), and because the plugin is patching the `auth()` function at runtime on the fastify instance, there doesn't appear to be many options available to resolve the local typing at the provider, as TypeScript is unaware of any type modifications made by the patch.

### Workaround

In the interim, the following should offer a workaround if using Type Providers (albeit a not ideal solution with the `any`). @TheWashiba this code was derived from your repro repository. You can preview the typing on this located [here](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgFQJ5gKZwL5wGZQQhwDkAAgM7AB2AxgDYCGwUA9DOhgEYQAeJAWABQoSLEQpOAIT5pMABUIA3YABMMUHPkLFyeRhRjA8qdpwC0YZWo3mOmHv2Gjo8fYeOoAggFcYAC20iUjJ3IxNWRj9-QRFwV3wDcNQg3TDPWJdxPDBU0nSTS3ofAHMaWOFWVjhzWrr6hsam5pbWtvbayur5YrLqLpqOoeGR0frhYQxeMXhaCGpDODBemjgAXnwwAAphODgtgtQASnWAPkRdvbg5hfgaQ0Y6LA3DgDoAd2AAuQxFCBV1FAADw-GS8H5-AEaU5bI4AbgmQiucHuMEetAwr0IfgwWwQl2RIAwAQgqgAXKQAOIAUWQJAANASrj4oPQKSRWMtSuVGUjkXAKLR-BgQIwKfi+fy4DxVKgKT9XgB5LgAKwwtBgeKZUrFkkwrwAcj4QFwNLDeVLkVx5ZxDcbTVBYdqrtgjs7sBb+VYMAAJR6qegaCmo9GYqIBLYAbQAuicDHBHqh6XAqnAYKSIBSoBgVBh3nASvQIFxGPQ4CBST5AwnSkTqGijPM4BA8GnhQKNEoNDWIyc8D46I3qK9nf5-YGoBSDKg6PtswBHZPZignNbnJDOvY3RZIRjJrhaDYL14ylLuz17V0Ivkey4S5HURhE9lTJ-LDAMy7YYTwxGpsYAYBQGdEIqYAJLUOovADMBsFwW0iLbvAFCdt2LxJJ4sIfF8-gQtYgIgtIsicJCNhQDCv5CChUBdlAWIYGUhhmocvgBJR1G0fRjEwGaXJ9G6VGoXR2I8VqfJEiS5JUrSn58iybKkKwsl7IKwqiuKTKnja+rKmqGpiVKvDaZiRommaRwXlccp6iZ9rmUyrpfp63p+pBE4UhxGivOG-hRrGCYUAm1BJim1TpqomZwNmub5oWxaluWlbVlEJR1g2wBNi2bZYJ5mg+bC+ADhqGXDpcY5uUGAUzrQc4YIuUUYCuZwXJK1zzDucC8MmKS4EedUnqSqBOcIV5AA).


```typescript
import { Type } from '@sinclair/typebox'
import { TypeBoxTypeProvider } from '@fastify/type-provider-typebox'
import fastifyAuth from '@fastify/auth'
import fastify from 'fastify'
import fp from 'fastify-plugin'

// --------------------------------------------------------------------------------
// Plugin
// --------------------------------------------------------------------------------

export const plugin = fp(
  (fastify) => {
    const instance = fastify.withTypeProvider<TypeBoxTypeProvider>();

    instance.route({
      method: 'GET',
      url: '/plugin',
      schema: {
        body: Type.Object({
          a: Type.Number(),
          b: Type.Number()
        })
      },
      preHandler: instance.auth([]) as any, // todo: review global module augmentation of the server auth() function.
      handler: async (req, res) => { 
        const { a, b } = req.body 
      },
    });
  },
  {
    name: 'example',
  }
);

// --------------------------------------------------------------------------------
// Index
// --------------------------------------------------------------------------------

const server = fastify().withTypeProvider<TypeBoxTypeProvider>();
server.register(fastifyAuth);
server.register(plugin)
server.route({
  method: 'GET',
  url: '/',
  schema: {
    body: Type.Object({
      x: Type.Number(),
      y: Type.Number()
    })
  },
  preHandler: server.auth([]) as any, // todo: review global module augmentation of the server auth() function.
  handler: async (req, res) => {
    const { x, y } = req.body
  },
});
```

### Possible Next Steps

I think probably the best way forward is spending some time taking a look at the way the current `server.auth([])` function definitions (potentially avoiding global module augmentation if possible). I think any investigations into this would likely be applicable for other plugin modules that augment the underlying `FastifyInstance`. So would make for good documentation for plugin authors writing TS definitions.

In terms of TypeScript, the ideal way to allow types to propagate would be to chain calls to `register()`, as follows. 

```typescript
const server = fastify()
 .withTypeProvider<TypeBoxTypeProvider>() // remap to generic TypeBoxTypeProvider
 .register(fastifyAuth)                   // augment instance with `.auth()` function.
 .register(plugin)                        // augment with user defined functionality.
 .route({                                 // route: configured with the above
   method: 'GET',
   url: '/',
   schema: {
     body: Type.Object({
       x: Type.Number(),
       y: Type.Number()
     })
   },
   preHandler: server.auth([]),
   handler: a sync (req, res) => {
     const {  x, y } = req.body
   }
  });
```
Although there may be additional options to explore with the following PR's

https://github.com/fastify/fastify/pull/3952 - Global augmentation of FastifyTypeProviderDefault
https://github.com/fastify/fastify/pull/4034 - Propagate generics from FastifyRegister

Hope that helps!
S

**Comment by climba03003** [comment]
> Regarding the fix on fastify-auth, go for it. It seems the generic one is better, but that's my 2 cents.

After digging to the root cause, I think there is no need to update the typing in `@fastify/auth`.
I see that it is using `^0.1.0-beta.1` is targeting to `fastify` github branch and application is targeting `fastify` in `npm`.
Update the packages to latest version should solve the issue.

**Comment by mcollina** [comment]
The change in fastify landed. I would like to close this and move the discussion about the follow-up in Fastify proper. Could you open such an issue @climba03003?

**Comment by irg1008** [comment]
Hi, I have searched and searched but It seems there is no clear solution to this specific problem yet.

**Comment by nahtnam** [comment]
Hi, just wanted to add onto this ticket here, I'm also unable to get it working without using `as any`. Here are the relevant snippets of code. Am I doing something wrong?

```ts
export const fastify = FastifyServer({}).withTypeProvider<ZodTypeProvider>();

fastify.decorate('verifyServerSecret', async (request: FastifyRequest) => {
  if (request.headers.authorization !== `Bearer ${env.SERVER_SECRET}`) {
    throw new UNAUTHORIZED("You don't have access to this endpoint");
  }
});

fastify.register(fastifyAuth);

declare module 'fastify' {
  interface FastifyInstance {
    verifyServerSecret: FastifyAuthFunction;  // technically this typing is wrong because I use `async/await` but it still works
  }
}

export type FastifyInstance = typeof fastify;
```

And then used like so:

```ts
fastify.route({
    method: 'POST',
    url: '/test',
    schema: {
      body: z.object({
        record: z.object({
          id: z.string(),
        }),
      }),
      response: {
        200: z.object({}),
      },
    },
    preHandler: fastify.auth([fastify.verifyServerSecret]), // adding `as any` here fixes it but doesn't seem right
    async handler(req) {
      const {
        record: { id },
      } = req.body; // ERROR: typed incorrectly :(

      return {};
    },
  });
```

**Comment by nahtnam** [comment]
Ideally I want to get more complicated and do something like this:

```ts
fastify.decorate('authenticateUser', async (request: FastifyRequest) => {
  // check headers and fetch user
  req.user = {} as User
});
```

where `req.user` is correctly typed:

```ts
fastify.route({
    // ...
    preHandler: fastify.auth([fastify.authenticateUser]),
    async handler(req) {
      // req.user works and is correctly typed but only on routes that define the `preHandler`
    },
  });
```

it this a possibility?

**Comment by m4rvr** [comment]
Why is this issue closes? Is there now a solution for this?

**Comment by nicobao** [comment]
`as any` conflicts with @fastify/swagger`, I get:
```bash
➜  back git:(main) ✗ pnpm ts-node --esm src/index.ts
[17:58:21 UTC] ERROR: Cannot read properties of undefined (reading 'typeName')
    err: {
      "type": "TypeError",
      "message": "Cannot read properties of undefined (reading 'typeName')",
      "stack":
          TypeError: Cannot read properties of undefined (reading 'typeName')
              at parseDef (/home/nicobao/zkorum/zkorum/services/back/node_modules/.pnpm/zod-to-json-schema@3.21.4_zod@3.21.4/node_modules/zod-to-json-schema/src/parseDef.js:45:46)
              at zodToJsonSchema (/home/nicobao/zkorum/zkorum/services/back/node_modules/.pnpm/zod-to-json-schema@3.21.4_zod@3.21.4/node_modules/zod-to-json-schema/src/zodToJsonSchema.js:16:48)
              at Object.transform (/home/nicobao/zkorum/zkorum/services/back/node_modules/.pnpm/fastify-type-provider-zod@1.1.9_fastify@4.19.2_zod@3.21.4/node_modules/fastify-type-provider-zod/dist/index.js:64:78)
              at Object.swagger (/home/nicobao/zkorum/zkorum/services/back/node_modules/.pnpm/@fastify+swagger@8.8.0/node_modules/@fastify/swagger/lib/spec/openapi/index.js:32:19)
              at file:///home/nicobao/zkorum/zkorum/services/back/src/index.ts:192:32
              at manageErr (/home/nicobao/zkorum/zkorum/services/back/node_modules/.pnpm/fastify@4.19.2/node_modules/fastify/fastify.js:583:11)
              at exit (/home/nicobao/zkorum/zkorum/services/back/node_modules/.pnpm/fastify@4.19.2/node_modules/fastify/lib/hooks.js:107:5)
              at manageTimeout (/home/nicobao/zkorum/zkorum/services/back/node_modules/.pnpm/fastify@4.19.2/node_modules/fastify/lib/hooks.js:124:11)
              at _encapsulateThreeParam (/home/nicobao/zkorum/zkorum/services/back/node_modules/.pnpm/avvio@8.2.1/node_modules/avvio/boot.js:562:7)
              at Boot.timeoutCall (/home/nicobao/zkorum/zkorum/services/back/node_modules/.pnpm/avvio@8.2.1/node_modules/avvio/boot.js:458:5)
    }
```

**Comment by ekoeryanto** [comment]
Hi, to prevent my self confused again.
the solution is only to cast to `never` or `any` the prehandler as it impact nothing
```ts
fastify.route({
    // ...
    preHandler: [] as never,
    // ...
  });
```

**Comment by JonRC** [comment]
Guys,  do that and your types will work as expected.

```TS
export const yourPreHandler = async <
  Request extends FastifyRequest,
  Reply extends FastifyReply
>(
  request: Request,
  reply: Reply
) => {
  // Your code here
};

```
